# Generated by Django 4.2.7 on 2023-11-28 04:58

from django.db import migrations, models
import django.db.models.deletion
import earsip_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KlasifikasiSurat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('klasifikasi', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'KlasifikasiSurat',
            },
        ),
        migrations.CreateModel(
            name='SemuaArsip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=20)),
                ('surat', models.CharField(max_length=10)),
                ('no_surat', models.CharField(max_length=20)),
                ('kepada', models.CharField(max_length=200)),
                ('tgl_surat', models.DateField()),
                ('perihal', models.CharField(max_length=200)),
                ('klasifikasi', models.CharField(max_length=30)),
                ('tanggal_dibuat', models.DateField()),
                ('upload_file_arsip', models.FileField(upload_to=earsip_app.models.user_folder)),
                ('is_read', models.CharField(max_length=2)),
                ('is_tu', models.CharField(max_length=2)),
                ('is_admin', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'SemuaArsip',
            },
        ),
        migrations.CreateModel(
            name='TempSuratKeluar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=20)),
                ('surat', models.CharField(max_length=10)),
                ('no_surat', models.CharField(max_length=20)),
                ('kepada', models.CharField(max_length=200)),
                ('tgl_surat', models.DateField()),
                ('perihal', models.CharField(max_length=200)),
                ('klasifikasi', models.CharField(max_length=30)),
                ('tanggal_dibuat', models.DateField()),
                ('upload_file_arsip', models.FileField(upload_to=earsip_app.models.user_folder)),
                ('is_read', models.CharField(max_length=2)),
                ('is_tu', models.CharField(max_length=2)),
                ('is_admin', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'SuratKeluar',
            },
        ),
        migrations.CreateModel(
            name='Disposisi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('no_agenda', models.TextField(max_length=40)),
                ('notes', models.TextField(max_length=200)),
                ('username', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=20)),
                ('upload_file_agenda', models.FileField(upload_to=earsip_app.models.user_folder)),
                ('is_read', models.CharField(max_length=2)),
                ('no_surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earsip_app.semuaarsip')),
            ],
            options={
                'db_table': 'Disposisi',
            },
        ),
    ]
