# Generated by Django 4.2.7 on 2023-11-22 01:05

from django.db import migrations, models
import earsip_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSurat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('group', models.CharField(max_length=20)),
                ('klasifikasi', models.CharField(max_length=30)),
                ('subklasifikasi', models.CharField(max_length=30)),
                ('tgl', models.DateField()),
                ('no_surat', models.TextField(max_length=200)),
                ('kepada', models.CharField(max_length=200)),
                ('perihal', models.CharField(max_length=200)),
                ('upload_file', models.FileField(upload_to=earsip_app.models.user_folder)),
            ],
            options={
                'db_table': 'DatabaseSurat',
            },
        ),
        migrations.CreateModel(
            name='DeleteSurat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('group', models.CharField(max_length=20)),
                ('klasifikasi', models.CharField(max_length=30)),
                ('subklasifikasi', models.CharField(max_length=30)),
                ('tgl', models.DateField()),
                ('no_surat', models.TextField(max_length=200)),
                ('kepada', models.CharField(max_length=200)),
                ('perihal', models.CharField(max_length=200)),
                ('upload_file', models.FileField(upload_to=earsip_app.models.user_folder)),
            ],
            options={
                'db_table': 'DeleteSurat',
            },
        ),
        migrations.CreateModel(
            name='KlasifikasiSurat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('group', models.CharField(max_length=20)),
                ('nama_klasifikasi', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'KlasifikasiSurat',
            },
        ),
        migrations.CreateModel(
            name='SubKlasifikasiSurat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('group', models.CharField(max_length=20)),
                ('nama_kelompok', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'SubKlasifikasiSurat',
            },
        ),
    ]
