# Generated by Django 4.2.7 on 2023-11-28 06:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('earsip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semuaarsip',
            name='surat_dari',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempsuratkeluar',
            name='no_agenda',
            field=models.TextField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disposisi',
            name='no_surat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='earsip_app.semuaarsip'),
        ),
    ]
