# Generated by Django 4.2.7 on 2023-11-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earsip_app', '0002_semuaarsip_surat_dari_tempsuratkeluar_no_agenda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSubBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag', models.CharField(max_length=255)),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
