# Generated by Django 4.2.7 on 2023-11-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earsip_app', '0002_alter_klasifikasisurat_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klasifikasisurat',
            old_name='nama_klasifikasi',
            new_name='klasifikasi',
        ),
        migrations.RenameField(
            model_name='subklasifikasisurat',
            old_name='nama_kelompok',
            new_name='subklasifikasi',
        ),
    ]
