# Generated by Django 4.2.7 on 2023-11-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earsip_app', '0003_checklistsubbag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempsuratkeluar',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='tempsuratkeluar',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='tempsuratkeluar',
            name='is_tu',
        ),
        migrations.RemoveField(
            model_name='tempsuratkeluar',
            name='no_agenda',
        ),
        migrations.AlterField(
            model_name='checklistsubbag',
            name='bag',
            field=models.CharField(max_length=30),
        ),
    ]
