# Generated by Django 4.2.7 on 2023-11-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earsip_app', '0004_remove_tempsuratkeluar_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempsuratkeluar',
            name='surat',
        ),
        migrations.RemoveField(
            model_name='tempsuratkeluar',
            name='tanggal_dibuat',
        ),
    ]
