# Generated by Django 4.2.7 on 2023-11-23 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('earsip_app', '0004_databasesurat_username_deletesurat_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasesurat',
            name='surat',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletesurat',
            name='surat',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
