# Generated by Django 4.2.7 on 2023-12-02 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('earsip_app', '0005_remove_semuaarsip_surat_dari'),
    ]

    operations = [
        migrations.AddField(
            model_name='semuaarsip',
            name='is_spri',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semuaarsip',
            name='surat_dari',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
