# Generated by Django 4.2.7 on 2023-12-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earsip_app', '0006_semuaarsip_is_spri_semuaarsip_surat_dari'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempSuratKeluar',
        ),
    ]
