# Generated by Django 4.2.7 on 2023-12-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earsip_app', '0007_delete_tempsuratkeluar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semuaarsip',
            name='is_admin',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='semuaarsip',
            name='is_read',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='semuaarsip',
            name='is_spri',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='semuaarsip',
            name='is_tu',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='semuaarsip',
            name='surat',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
